# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test DrissionPage

on:
  # schedule:
    # - cron: '*/30 * * * *' # run every 30 minutes
#   - cron: '0 * * * *' # run every 60 minutes
  workflow_dispatch: # be able to optionally run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the proxy scraper
      run: |
        python ScrapeAllProxies.py --output test/scraped-proxies.txt --only OpenProxyList -v
    # - name: Run the proxy checker
    #   run: |
    #     python CheckProxies.py --input test/scraped-proxies.txt --output test/working-proxies.txt --threads 3000 --timeout 2s
    # commit the changes
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Re-scrape proxies"
        file_pattern: "test/scraped-proxies.txt test/working-proxies-*.txt" # only commit the matching files
